name: potty_feeding_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: 2.4.1
  get_it: ^7.6.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  i18n: ^4.1.0
  i69n: ^2.1.0
  injectable: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true